name: Laravel

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  lint:
    name: Lint (PHP ${{ matrix.php-versions }} on ubuntu-latest
    strategy:
      matrix:
        php-versions: [ "8.1" ]
    timeout-minutes: 5

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP, with composer and extensions
        uses: shivammathur/setup-php@v2 #https://github.com/shivammathur/setup-php
        with:
          php-version: ${{ matrix.php-versions }}

      - name: config composer for nova
        run: composer config "http-basic.nova.laravel.com" "${{ secrets.NOVA_USERNAME }}" "${{ secrets.NOVA_LICENSE_KEY }}"

      - name: Install dependencies
        uses: "ramsey/composer-install@v2"
        with:
          composer-options: "--prefer-dist --optimize-autoloader"

      - name: Validate composer.json and composer.lock
        run: composer validate --strict

      - name: Run Pint 🍺 Linter
        run: composer lint:test
